version: '3.8'

services:
  auth-server:
    build: ./auth-server
    ports:
      - "5001:5001"
    depends_on:
      - database

  converter-module:
    build: ./converter-module
    depends_on:
      - rabbitmq

  database:
    build: ./database-server
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: conversion_db

  notification-server:
    build: ./notification-server
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
