apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-server
  template:
    metadata:
      labels:
        app: notification-server
    spec:
      containers:
      - name: notification
        image: your-dockerhub-username/notification-server:latest
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-server
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: NodePort
